### PR TITLE
Add support for building g++-1.27

### PR DESCRIPTION
**Pull request by narpfel**
This builds a functional (?) `g++ version 1.27.0` (dated 1988-09-14) with some minor changes:
* `.cpp` has been added as an extension for C++ code (otherwise `g++` would try to call the linker with `.cpp` files).
* `g++` requires a custom linker to collect/call global constructors and destructors. However, this linker only supports the `a.out` file format and can’t link with the `crt1.o` provided by the system. As a workaround, global ctors and dtors are called via `.init_array`/`.fini_array` and the system linker is used.
* Support for the `-Wl,...` command line flag has been added so that execution works.
* `libg++` is not included, so there is no standard library.

This requires #28 because the `g++` build reuses some `gcc-1.27` source files that must be patched to build on Ubuntu 22.04.

### CODE REVIEW

File: build/build-g++-1.27.sh [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+        pushd $1
+        for PATCH in ${PATCH_DIR}/*; do
+            echo "...${PATCH}"
+            patch -p1 <${PATCH}
+        done
+        popd
+    fi
+}
+
+applyPatches gcc-1.27 gcc${MAJOR_MINOR}
```
Comment (dkm) [inline build/build-g++-1.27.sh]: I guess some "1.27" could be replaced by ${MAJOR_MINOR} as you already have that in other places?

File: build/build-g++-1.27.sh [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+
+OUTPUT=/root/g++-${VERSION}.tar.xz
+S3OUTPUT=""
+if echo $2 | grep s3://; then
+    S3OUTPUT=$2
+else
+    OUTPUT=${2-/root/g++-${VERSION}.tar.xz}
+fi
+
+# Workaround for Ubuntu builds
```
Comment (dkm) [inline build/build-g++-1.27.sh]: I don't remember what issue this workaround is for. Have you tried to see if it's still needed?

**Comment by dkm** [comment]
Looks very nice, thanks! Any chance this could be merged with the build-1.27 script? Both look very similar.

File: build/build-g++-1.27.sh (hunk 2 above)
Comment (narpfel) [reply build/build-g++-1.27.sh]: I haven’t, but given that it sets a 64-bit library path, I suspect that it doesn’t do anything for `g++-1.27` and `gcc-1.27`.

**Comment by narpfel** [comment]
> Any chance this could be merged with the build-1.27 script? Both look very similar.

Do you mean that the combined script should build both in one invocation or that it should be called for each separately?

File: build/build-g++-1.27.sh (hunk 1 above)
Comment (narpfel) [reply build/build-g++-1.27.sh]: Done: a68bf39e9a65d863c0b3fd94c85a1e419421cea4

File: build/build-g++-1.27.sh (hunk 2 above)
Comment (narpfel) [reply build/build-g++-1.27.sh]: As expected it has no effect, removed in c99e12ec6967f62d0f19dfbedc57ae213826201e.

**Comment by dkm** [comment]
> > Any chance this could be merged with the build-1.27 script? Both look very similar.
> 
> Do you mean that the combined script should build both in one invocation or that it should be called for each separately?

Avoid any duplication is the goal... And I don't think there's any reason we want to have separate gcc / g++ here.

I see that you have an infra change. The "c compiler" 1.27 and the "c++ compiler" can be installed together, they are really different packages? Or is the c++ a superset of the c one and we could have only this new package installed instead of both?

If the latter, then we could overwrite the existing C-only compiler and keep only one build script.

Does that make sense?

**Comment by narpfel** [comment]
I merged the two builds in 83150caf56891e2be6bca8e050dafd7230203c53. It turns out that that’s actually the correct way to install `g++`: It expects to be installed into the same prefix as `gcc` because it reuses the headers in `$prefix/lib/gcc-include`.

**Comment by dkm** [comment]
> I merged the two builds in [83150ca](https://github.com/compiler-explorer/gcc-builder/commit/83150caf56891e2be6bca8e050dafd7230203c53). It turns out that that’s actually the correct way to install `g++`: It expects to be installed into the same prefix as `gcc` because it reuses the headers in `$prefix/lib/gcc-include`.

ok, nice then! Looks like it's good to go! But this means that we will overwrite the existing gcc 1.27 by this new one that "only" adds the g++ compiler. Are we OK with that @mattgodbolt ? I know we avoid "changing" things, but here, it should not change things for existing links on 1.27. 
If not, then we need to install this new combined compiler in a different path and only have the c++ config point at it (and keep the gcc 1.27 config pointing at the old one).

**Comment by narpfel** [comment]
> but here, it should not change things for existing links on 1.27.

Yes, the existing `gcc` installation is not changed (apart from the changes from #28; `gcc` does not know anything about `g++`), there are just some additional independent files installed into the same prefix:

Old:
```console
$ tree /opt/compiler-explorer/gcc-1.27
/opt/compiler-explorer/gcc-1.27
├── bin
│   └── gcc
└── lib
    ├── gcc-cc1
    ├── gcc-cpp
    ├── gcc-gnulib
    └── gcc-include
        ├── assert.h
        ├── limits.h
        ├── stdarg.h
        ├── stddef.h
        ├── varargs.h
        ├── va-sparc.h
        └── va-spur.h
```

New:
```console
$ tree /tmp/gcc
/tmp/gcc
├── bin
│   ├── g++
│   └── gcc
└── lib
    ├── crt0+.o
    ├── crt1+.o
    ├── gcc-c++
    ├── gcc-cc1
    ├── gcc-cpp
    ├── gcc-cpp+
    ├── gcc-gnulib
    ├── gcc-gnulib+
    ├── gcc-include
    │   ├── assert.h
    │   ├── limits.h
    │   ├── stdarg.h
    │   ├── stddef.h
    │   ├── varargs.h
    │   ├── va-sparc.h
    │   └── va-spur.h
    └── gcc-ld++
```

**Comment by dkm** [comment]
Ok, sounds good then. I'll merge, then I'll rebuild the compiler and install this new archive over previous install :+1: Thanks!

**Comment by dkm** [comment]
Kicked off a build: https://github.com/compiler-explorer/infra/actions/runs/19043023196

**Comment by dkm** [comment]
And with a correct command: https://github.com/compiler-explorer/infra/actions/runs/19043352662/job/54385597373

**Comment by dkm** [comment]
```
3238   │ 2025-11-03T17:25:32.9093645Z gcc.c: In function 'pfatal_with_name':
3239   │ 2025-11-03T17:25:32.9093789Z gcc.c:1223:15: error: 'sys_nerr' undeclared (first use in this function)
3240   │ 2025-11-03T17:25:32.9093855Z  1223 |   if (errno < sys_nerr)
3241   │ 2025-11-03T17:25:32.9094118Z       |               ^~~~~~~~
3242   │ 2025-11-03T17:25:32.9094392Z cccp.c:913:3: warning: implicit declaration of function 'file_size_and_mode' [-Wimplicit-function-declaration]
3243   │ 2025-11-03T17:25:32.9094489Z   913 |   file_size_and_mode (f, &st_mode, &st_size);
3244   │ 2025-11-03T17:25:32.9094552Z       |   ^~~~~~~~~~~~~~~~~~
3245   │ 2025-11-03T17:25:32.9094785Z toplev.c:833:3: warning: implicit declaration of function 'yyparse' [-Wimplicit-function-declaration]
3246   │ 2025-11-03T17:25:32.9094848Z   833 |   yyparse ();
3247   │ 2025-11-03T17:25:32.9094911Z       |   ^~~~~~~
3248   │ 2025-11-03T17:25:32.9095123Z gcc.c:1223:15: note: each undeclared identifier is reported only once for each function it appears in
3249   │ 2025-11-03T17:25:32.9095387Z cccp.c:931:13: warning: implicit declaration of function 'read'; did you mean 'fread'? [-Wimplicit-function-declaration]
3250   │ 2025-11-03T17:25:32.9095487Z   931 |       cnt = read (f, bufp, bsize - size);
3251   │ 2025-11-03T17:25:32.9095547Z       |             ^~~~
3252   │ 2025-11-03T17:25:32.9095621Z       |             fread
3253   │ 2025-11-03T17:25:32.9095892Z c-parse.y:1101:17: warning: implicit declaration of function 'push_parm_decl' [-Wimplicit-function-declaration]
3254   │ 2025-11-03T17:25:32.9095977Z  1101 |                 { push_parm_decl ($1); }
3255   │ 2025-11-03T17:25:32.9096047Z       |                 ^~~~~~~~~~~~~~
3256   │ 2025-11-03T17:25:32.9096220Z bison.simple:314:24: warning: too many arguments for format [-Wformat-extra-args]
3257   │ 2025-11-03T17:25:32.9096363Z gcc.c:1224:21: error: 'sys_errlist' undeclared (first use in this function)
3258   │ 2025-11-03T17:25:32.9096472Z  1224 |     s = concat ("", sys_errlist[errno], " for %s");
3259   │ 2025-11-03T17:25:32.9096538Z       |                     ^~~~~~~~~~~
```

@narpfel looks like something is not working as expected. Did it work for you in the container?

**Comment by narpfel** [comment]
#28 is also needed for `gcc` to build on Ubuntu 22.04. With that merged it should work.

**Comment by dkm** [comment]
Ah sorry, of course. Applied now, will start a new build later. Thanks! :+1:

**Comment by narpfel** [comment]
Ah, I missed building `gnulib+` so it still doesn’t quite work: https://github.com/compiler-explorer/infra/actions/runs/19046487850/job/54395869328

**Comment by narpfel** [comment]
Should be fixed by #32.

**Comment by mattgodbolt** [comment]
Building: https://github.com/compiler-explorer/infra/actions/runs/19073117509

**Comment by mattgodbolt** [comment]
```
2025-11-04T15:08:10.1572935Z /opt/compiler-explorer/gcc-build
2025-11-04T15:08:10.1573221Z + export 'XZ_DEFAULTS=-T 0'
2025-11-04T15:08:10.1573472Z + XZ_DEFAULTS='-T 0'
2025-11-04T15:08:10.1573854Z + tar Jcf /dist --transform 's,^./,./gcc-1.27/,' -C /opt/compiler-explorer/gcc-1.27 .
2025-11-04T15:08:10.1583954Z tar (child): /dist: Cannot open: Is a directory
2025-11-04T15:08:10.1584481Z tar (child): Error is not recoverable: exiting now
2025-11-04T15:08:10.1612602Z tar: Child returned status 2
2025-11-04T15:08:10.1612869Z tar: Error is not recoverable: exiting now
2025-11-04T15:08:10.2895068Z ##[error]Process completed with exit code 2.
2025-11-04T15:08:10.2978387Z Post job cleanup.
2025-11-04T15:08:10.3829424Z [command]/usr/bin/git version
2025-11-04T15:08:10.3860051Z git version 2.34.1
```

Hmm something;s up here. Will investigate

**Comment by mattgodbolt** [comment]
Fixed and built! installing now!
